//Movies
export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';

export const LOADE_MORE_MOVIES_START = 'LOADE_MORE_MOVIES_START';
export const LOADE_MORE_MOVIES_SUCCESS = 'LOADE_MORE_MOVIES_SUCCESS';
export const LOADE_MORE_MOVIES_FAIL = 'LOADE_MORE_MOVIES_FAIL';


export const FETCH_MOVIE_START = 'FETCH_MOVIE_START';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAIL = 'FETCH_MOVIE_FAIL';

export const FETCH_STAR_SUCCESS = 'FETCH_STAR_SUCCESS';
export const FETCH_STAR_FAIL = 'FETCH_STAR_FAIL';

export const FETCH_CASTS_START = 'FETCH_CASTS_START';
export const FETCH_CASTS_SUCCESS = 'FETCH_CASTS_SUCCESS';
export const FETCH_CASTS_FAIL = 'FETCH_CASTS_FAIL';

export const FETCH_TRAILERS_START = 'FETCH_TRAILERS_START';
export const FETCH_TRAILERS_SUCCESS = 'FETCH_TRAILERS_SUCCESS';
export const FETCH_TRAILERS_FAIL = 'FETCH_TRAILERS_FAIL';

//Tv Shows
export const FETCH_SHOWS_START = 'FETCH_SHOWS_START';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_FAIL = 'FETCH_SHOWS_FAIL';

export const LOADE_MORE_SHOWS_SUCCESS = 'LOADE_MORE_SHOWS_SUCCESS';