//Movies
export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';

export const LOADE_MORE_MOVIES_START = 'LOADE_MORE_MOVIES_START';
export const LOADE_MORE_MOVIES_SUCCESS = 'LOADE_MORE_MOVIES_SUCCESS';
export const LOADE_MORE_MOVIES_FAIL = 'LOADE_MORE_MOVIES_FAIL';